name: Generate Pacman

on:
  schedule:
    - cron: "0 */12 * * *" # Update setiap 12 jam
  workflow_dispatch: # Bisa dijalankan manual
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Pacman Animation
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: sepkascurty-cpu
          template: classic
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          # Config khusus visual pacman
          config_timezone: Asia/Jakarta
          config_order: isocalendar
